---
name: tox-pytest

on: [push, pull_request]

jobs:
  ci-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.13", "3.14"]
      fail-fast: false
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 2

      - name: Set up conda environment for testing
        uses: mamba-org/setup-micromamba@v3
        with:
          environment-file: environment.yml
          cache-environment: true
          condarc: |
            channels:
            - conda-forge
            channel_priority: strict

      - shell: bash -l {0}
        run: |
          conda info
          conda list
          conda config --show-sources
          conda config --show
          printenv | sort

      - name: Set default gcp credentials
        id: gcloud-auth
        continue-on-error: true
        uses: "google-github-actions/auth@v2"
        with:
          # you'll need to update the WIF setup in pudl/terraform to allow actions from this repo to access the tox-pytest service account!
          workload_identity_provider: "projects/345950277072/locations/global/workloadIdentityPools/gh-actions-pool/providers/gh-actions-provider"
          service_account: "tox-pytest-github-action@catalyst-cooperative-pudl.iam.gserviceaccount.com"

      - name: Run PyTest with Tox
        run: |
          tox

      - name: Upload test coverage report to CodeCov
        uses: codecov/codecov-action@v6
